box: mchakravarty/ghc-7.10.2
build:
  steps:
  - script:
    name: install
    code: cabal update && cabal install && cabal install hspec
  - script:
      name: cabal
      code: cabal test --ghc-option=-fsimpl-tick-factor=130
